development:
  adapter: postgresql
  encoding: unicode
  database: epoch_development
  pool: 5
  username: epoch
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: epoch_test
  pool: 5
  username: epoch
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: epoch_production
  pool: 5
  username: epoch
  password:
  timeout: 5000
